name: Deploy to Development

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  PROJECT_ID: archie-465300
  GAR_LOCATION: us-west1
  REPOSITORY: archie
  SERVICE: archie
  REGION: us-west1-a

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Install dependencies and run tests
      run: |
        uv sync --extra dev
        uv run ruff check backend/
        uv run ruff format backend/ --check
        cd backend && uv run pytest -v

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        install_components: 'gke-gcloud-auth-plugin'

    - name: Configure Docker for GAR
      run: gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev

    - name: Install kustomize
      run: |
        if ! command -v kustomize &> /dev/null; then
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/
        fi

    - name: Get cluster credentials
      run: |
        gcloud container clusters get-credentials archie-dev --zone=$REGION
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True

    - name: Build and push Docker image
      run: |
        IMAGE_TAG=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:${{ github.sha }}
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG

    - name: Create namespaces
      run: |
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        kubectl apply -f k8s/setup-namespaces.yaml

    - name: Deploy to GKE
      run: |
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        cd k8s/dev
        kustomize edit set image archie-app=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:${{ github.sha }}
        kubectl apply -k .

    - name: Verify deployment
      run: |
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        echo "Waiting for deployment rollout to complete..."
        kubectl rollout status deployment/archie-deployment -n dev --timeout=300s
        
        echo "Waiting for pods to be ready..."
        kubectl wait --for=condition=ready pod -l app=archie -n dev --timeout=300s
        
        echo "Checking pod status..."
        kubectl get pods -n dev
        
        echo "Checking if any pods are in error states..."
        if kubectl get pods -n dev -o jsonpath='{.items[*].status.containerStatuses[*].state}' | grep -E '(waiting|terminated)'; then
          echo "Some pods are not running properly. Checking logs..."
          kubectl describe pods -n dev
          exit 1
        fi
        
        echo "Testing API endpoint..."
        kubectl port-forward -n dev svc/archie-service 8080:80 &
        sleep 5
        curl -f http://localhost:8080/api/time || exit 1
        pkill -f "kubectl port-forward"
        
        echo "Deployment verification successful!"
        kubectl get services -n dev