name: Deploy to Staging

on:
  workflow_run:
    workflows: ["Deploy to Development"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:

env:
  PROJECT_ID: archie-465300
  GAR_LOCATION: us-west1
  REPOSITORY: archie
  SERVICE: archie
  REGION: us-west1-a

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker for GAR
      run: gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev

    - name: Get cluster credentials
      run: |
        gcloud container clusters get-credentials archie-staging --zone=$REGION

    - name: Deploy to GKE
      run: |
        cd k8s/staging
        kustomize edit set image archie-app=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:${{ github.sha }}
        kubectl apply -k .

    - name: Verify deployment
      run: |
        kubectl rollout status deployment/archie-deployment -n staging --timeout=300s
        kubectl get services -n staging